name: Deploy Website to AWS

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Build application
        run: yarn build
      - name: Deploy to S3
        run: aws s3 sync --delete ./dist/ s3://${{ secrets.BUCKET_ID }}
      - name: Set S3 Cache-Control metadata to images
        run: aws s3 cp s3://${{ secrets.BUCKET_ID }} s3://${{ secrets.BUCKET_ID }} --recursive --metadata-directive REPLACE --cache-control max-age=86400 --exclude "*" --include "*.jpg" --include "*.png" --include "*.webp"
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
